### PR TITLE
fix: welcome page no longer loads multiple times

### LINKED ISSUE #112: (Firefox) Welcome page pops up randomly if enabled
Manifest version 3 changes persistent background pages to service workers, which has the following side effect:

> Service workers are ephemeral, which means they'll likely start, run, and terminate repeatedly during a user's browser session. It also means that data is not immediately available in global variables since the previous context was torn down. [^1]

Due to this, [this line in backend.js](https://github.com/themoeway/yomitan/blob/451b7f429414bedeb0e363b474c9b43429c48045/ext/js/background/backend.js#L241) keeps getting ran, and opens up the welcome page pretty much arbitrarily.

As noted in the mv3 migrating page, a potential solution is to use [`chrome.storage`](https://developer.chrome.com/docs/extensions/reference/storage/#storage-areas) (and in particular, [`storage.session`](https://developer.chrome.com/docs/extensions/reference/storage/#property-session))

~~Only tested on Chromium so far, unsure if the behaviour is the same on Firefox.~~
Fixed for Chrome in #113, but bug still exists for Firefox.

[^1]:  https://developer.chrome.com/docs/extensions/migrating/to-service-workers/#persist-states

### PR DESCRIPTION
**Pull request by Aquafina-water-bottle**
Fixes #112. However, this is pretty much a band-aid fix for one small problem. We might want to look further into #114 to see if there is a better way of fixing the non-persistent extension issue overall.

### CODE REVIEW

File: ext/js/background/backend.js [hunk 1]
```diff
@@ -2152,6 +2152,21 @@ class Backend {
         return textReplacements;
     }
 
+    async _openWelcomeGuidePageOnce() {
+        if (isObject(chrome.storage) && isObject(chrome.storage.session)) {
```
Comment (djahandarie) [inline ext/js/background/backend.js:2156]: Mmm, so Firefox doesn't support `storage.session` -- but on the other hand it's a background page and not a SW so we won't have this issue there in the first place, so it's okay.

Could you fix the comment to show that Chrome will end up in the top branch and Firefox will end up in the bottom branch?

File: ext/js/background/backend.js [hunk 2]
```diff
@@ -2152,6 +2152,21 @@ class Backend {
...
+            chrome.storage.session.get(['openedWelcomePage']).then((result) => {
+                console.log(new Date(), 'openedWelcomePage:', result.openedWelcomePage);
```
Comment (djahandarie) [inline ext/js/background/backend.js:2158]: Currently I don't believe the extension ever does a `console.log` in a non-error condition. But I think it's fine to leave some sort of debugging information in the SW.

Maybe we could consider `console.info` for intentionally leaving informational messages (like https://stackoverflow.com/a/45766458 suggests)?

**Review by djahandarie — CHANGES_REQUESTED** [review]

File: ext/js/background/backend.js (hunk 2 above)
Comment (Aquafina-water-bottle) [reply ext/js/background/backend.js:2158]: Oh this was entirely my bad, I accidentally left this in the PR. It's probably best to remove this for now, to conform with the rest of the extension.

File: ext/js/background/backend.js (hunk 1 above)
Comment (Aquafina-water-bottle) [reply ext/js/background/backend.js:2156]: Oh good catch. It seems like the bug remains on Firefox, since the background page is no longer persistent either. I'm not aware of another solution outside of `storage.session`, so the bug will remain on Firefox until it gets implemented.

Comment (djahandarie) [reply ext/js/background/backend.js:2156]: :smiling_face_with_tear:

**Comment by djahandarie** [comment]
@Aquafina-water-bottle Any chance you could rebase this on master cleanly without having the merge commit?

**Review by djahandarie — APPROVED** [review]
