### PR TITLE
Fix Chrome death, by creating both cross-frame ports in the background

### LINKED ISSUE #241: Yomitan popup window fails to update, repeatedly showing the same dictionary entry
**Description**
After using Yomitan for a reasonable amount of time on a single HTML page, occasionally the popup window gets "stuck", showing the same dictionary entries no matter what word you hover over. Notice how no matter what word I hover over, the dictionary entries for 王国 are all that show up.

https://github.com/themoeway/yomitan/assets/20632064/ccdab51a-f55d-4336-ae5e-afd5852eced0

This can be worked around by refreshing the HTML page you're on whenever it happens. I don't know how to reproduce it reliably yet, but on a fresh profile of chrome with a new install of yomitan with just JMDict (I didn't mess with the default settings), I can **sometimes** reproduce it through some combination of hovering over a word, opening up a new tab, coming back after 30 seconds to 5 minutes, and discovering that I somehow got into this state.

After the problem appears, I start to get errors in my dev console like these (requires you to un-ignore yomitan's content scripts before you can debug/see these errors in the console):
image
```
cross-frame-api.js:173 Uncaught (in promise) Error: Acknowledgement timeout (popupMessage)
    at CrossFrameAPIPort._onError (cross-frame-api.js:173:21)
    at cross-frame-api.js:65:62
_onError	@	cross-frame-api.js:173
(anonymous)	@	cross-frame-api.js:65
await in (anonymous) (async)		
clearAutoPlayTimer	@	popup.js:320
_clearSelection	@	frontend.js:356
_onTextScannerClear	@	frontend.js:311
trigger	@	core.js:409
_triggerClear	@	text-scanner.js:1178
_onMouseDown	@	text-scanner.js:434
```
```
cross-frame-api.js:173 Uncaught (in promise) Error: Acknowledgement timeout (popupMessage)
    at CrossFrameAPIPort._onError (cross-frame-api.js:173:21)
    at cross-frame-api.js:65:62
_onError	@	cross-frame-api.js:173
(anonymous)	@	cross-frame-api.js:65
await in (anonymous) (async)		
showContent	@	popup.js:304
await in showContent (async)		
_showPopupContent	@	frontend.js:613
_showContent	@	frontend.js:603
_onSearched	@	frontend.js:332
trigger	@	core.js:409
_search	@	text-scanner.js:373
await in _search (async)		
_searchAt	@	text-scanner.js:952
await in _searchAt (async)		
_searchAtFromMouseMove	@	text-scanner.js:975
_onMouseMove	@	text-scanner.js:418
```

**Browser version**
Chrome 117.0.5938.62

**Yomichan version**
23.4.7.0 (I downloaded the master branch at commit https://github.com/themoeway/yomitan/commit/94ccff4c790ae8c2ef301bdb4e593f51436b3c8e and loaded the unpacked extension)

### PR DESCRIPTION
**Pull request by praschke**
on Chrome (currently 117), the port created in the content script with runtime.connect does not properly receive an onDisconnect event when the service worker sleeps. the port created in the background with tabs.connect does receive the event, so create both ports with tabs.connect.

fixes #241.

### CODE REVIEW

File: ext/js/comm/cross-frame-api.js [hunk 1]
```diff
@@ -297,14 +300,16 @@ class CrossFrameAPI {
         return this._createCommPort(otherTabId, otherFrameId);
     }
 
-    _createCommPort(otherTabId, otherFrameId) {
-        const details = {
-            name: 'background-cross-frame-communication-port',
-            targetTabId: otherTabId,
-            targetFrameId: otherFrameId
-        };
-        const port = yomichan.connect(null, {name: JSON.stringify(details)});
```
Comment (djahandarie) [inline ext/js/comm/cross-frame-api.js:306]: I think this is the only usage of `yomichan.connect`, so maybe it can be removed in this change?

File: ext/js/background/backend.js [hunk 2]
```diff
@@ -2273,4 +2219,48 @@ class Backend {
...
+        const targetDetails = {
+            name: 'cross-frame-communication-port',
+            otherTabId: sourceTabId,
+            otherFrameId: sourceFrameId
+        };
+        let sourcePort = chrome.tabs.connect(sourceTabId, {frameId: sourceFrameId, name: JSON.stringify(sourceDetails)});
+        let targetPort = chrome.tabs.connect(targetTabId, {frameId: targetFrameId, name: JSON.stringify(targetDetails)});
+
+        const cleanup = () => {
+            console.log('cross-frame cleanup', targetPort, sourcePort);
```
Comment (djahandarie) [inline ext/js/background/backend.js:2247]: I think this should be `log.log` judging by how logging works in the rest of the extension (or removed in the case it's a forgotten debugging statement).

**Review by djahandarie — DISMISSED** [review]
Thank you so much, this looks like it will be the key PR for getting yomitan released. Left some minor comments, feel free to resolve them however you see fit.

File: ext/js/background/backend.js (hunk 2 above)
Comment (praschke) [reply ext/js/background/backend.js:2247]: missed this one, thanks

**Review by djahandarie — APPROVED** [review]
:tada:
