### PR TITLE
Fix google docs

### LINKED ISSUE #235: Google Docs compatibility mode not working
**Description**
I didn't see anyone else report this, so am not sure if it is just me, but Google Docs compatibility mode seems to have stopped working. I tried reinstalling Yomitan, restarting browser, refreshing Google doc pages, but it doesn't work anymore, however it works fine on any other page.

I know the setting in Yomitan says that this could happen at anytime due to changes made by Google.

**Browser version**
Firefox 116.0.3

**Yomichan version**
Yomitan 23.8.19.0

### LINKED ISSUE #451: Google Docs Compatibility Mode stopped working
**Description**
Cannot scan text using Yomitan, even after enabling Google docs compatibility mode.
image

**Browser version**
Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Yomitan version**
23.11.23.0 Yomitan (development build)

**Exported settings file**
[yomitan-settings-2023-12-26-06-56-10.json](https://github.com/themoeway/yomitan/files/13769346/yomitan-settings-2023-12-26-06-56-10.json)

### PR DESCRIPTION
**Pull request by toasted-nutbread**
Fixes #451.
Fixes #235.

### CODE REVIEW

File: ext/js/accessibility/google-docs-xray.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ */
+
+/** Entry point. */
+function main() {
+    /** @type {Window} */
+    // @ts-expect-error - Firefox Xray vision
+    const window2 = window.wrappedJSObject;
+    if (!(typeof window2 === 'object' && window2 !== null)) { return; }
+    // The extension ID below is on an allow-list that is used on the Google Docs webpage.
+    // @ts-expect-error - Adding a property to the global object
```
Comment (djahandarie) [inline ext/js/accessibility/google-docs-xray.js:25]: Would it be better to extend the window's type definition using declare global? At least that way we can get type checking on what we are trying to store in the variable, and avoid issues like variable typos or logic errors doing a refactor.

Comment (toasted-nutbread) [reply ext/js/accessibility/google-docs-xray.js:25]: It could be but I didn't because it was already a one-off (now a two-off) thing in the code, that realistically has no need to be exposed everywhere else in the codebase, which will happen if a typescript interface is added.

File: ext/js/accessibility/google-docs-xray.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    // eslint-disable-next-line no-underscore-dangle
+    window2._docs_annotate_canvas_by_ext = 'ogmnaimimemjmbakcfefmnahgdfhfami';
```
Comment (djahandarie) [inline ext/js/accessibility/google-docs-xray.js:27]: Isn't this the old yomichan ID? Plus, maybe we should make this dynamic somehow (https://developer.chrome.com/docs/extensions/reference/api/runtime#property-id ?), such that it works regardless of whether you're on stable/dev/unpacked

Comment (toasted-nutbread) [reply ext/js/accessibility/google-docs-xray.js:27]: Yomichan's ID is in a whitelist that is hardcoded into the Google's source code, I don't think it works with any random value.

Comment (djahandarie) [reply ext/js/accessibility/google-docs-xray.js:27]: Oh... does that mean we can't even fix this unless we ask Google to change their whitelist to point to [`likgccmbimhjbgkjambclfkhldnlhbnn`](https://chromewebstore.google.com/detail/yomitan/likgccmbimhjbgkjambclfkhldnlhbnn)? Or does it not actually matter? It seems I'm a bit confused about how this functionality works...

Comment (toasted-nutbread) [reply ext/js/accessibility/google-docs-xray.js:27]: You can search for it in here for example: (the number in the URL probably changes over time)
https://docs.google.com/static/document/client/js/1799341870-client_js_prod_kix_core.js

Comment (toasted-nutbread) [reply ext/js/accessibility/google-docs-xray.js:27]: You can use the ID from another extension without issue.

Comment (toasted-nutbread) [reply ext/js/accessibility/google-docs-xray.js:27]: The only thing that the google docs script does is check to see if the value of `_docs_annotate_canvas_by_ext` is in their whitelist. It has no way of actually validating that the extension is installed, or that it is the one that set the value. The worst that could happen is that Google denies the extension store submission, but that is very unlikely, especially as this extension is a derivative of the original and there is currently only a testing version publicly available.

**Review by djahandarie — APPROVED** [review]
