### PR TITLE
Fix tags not displaying for duplicate cards

### LINKED ISSUE #817: Show card tags feature not working
**Description**
Show card tags doesn't seem to be working on the latest stable release 24.4.7.0:
image

Works as expected on 24.01.14.0:
image

**Browser version**
Firefox 124.0.2 (64-bit)

**Yomitan version**
24.4.7.0

### PR DESCRIPTION
**Pull request by Kuuuube**
Fixes #817

cannotAdd is no longer a possible differentiator for if a card is a dupe and cannot be used to check whether notesInfo needs to be pulled.

### CODE REVIEW

**Review by StefanVukovic99 — APPROVED** [review]

File: ext/js/background/backend.js [hunk 1]
```diff
@@ -622,20 +626,6 @@ export class Backend {
             }
```
Comment (jamesmaa) [inline ext/js/background/backend.js:626]: Where is `cannotAdd` being used?

File: ext/js/background/backend.js [hunk 2]
```diff
@@ -609,10 +609,14 @@ export class Backend {
 
             const valid = isNoteDataValid(note);
 
+            const noteIds = isDuplicate ? duplicateNoteIds[originalIndices.indexOf(i)] : null;
+            const noteInfos = (fetchAdditionalInfo && noteIds !== null && noteIds.length > 0) ? await this._anki.notesInfo(noteIds) : [];
+
             const info = {
```
Comment (jamesmaa) [inline ext/js/background/backend.js:615]: Is it possible to make this dict typed? Not sure how this is being consumed by the caller of `_onApiGetAnkiNoteInfo`

**Review by jamesmaa — APPROVED** [review]
LGTM. Just some questions for my own edification

File: ext/js/background/backend.js (hunk 1 above)
Comment (jamesmaa) [reply ext/js/background/backend.js:626]: Yeah but I don't see `cannotAdd` being consumed within the function scope or am I blind?

Comment (Kuuuube) [reply ext/js/background/backend.js:626]: It's possible it may be able to be removed entirely.
